- README.md
**READY/IN DEVELOPMENT/HOLD**
YES | NO
A few sentences describing the overall goals of the pull request's commits.
List related PRs against other branches:
branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.
Outline the steps to test or reproduce the PR here.
```sh
git pull --prune
git checkout <feature_branch>
bundle; script/server
```
1. 
List general components of the application that this PR will affect:
*
> chore: Change License and Contributing description

- src/app.ts
- src/client/client.controller.ts
- src/client/client.repository.ts
- src/client/client.router.ts
- src/config.ts
- src/oauth2/oauth2.controller.ts
- src/oauth2/oauth2.parser.ts
- src/utils/error.handler.ts
**READY**
YES
That PR Includes:
- Fix integration errors with `authorization-server` client management API.
- Fix error handler to include error responses from `authorization-server`. 
- Fix client management REST API to include `clientId` request parameter in read, update and delete requests.
- Improve client delete response, return 204 (No-Content) status code.
- Adding client manager authentication for authorization server API
For now, every time you restart the server after using the `authorization-server` API, you should delete the `access token`  that created in the `authorization-server` db for using the API again.
List general components of the application that this PR will affect:
* Client Management API with `authorization-server`.
* Client Management API with …
> Fix authorization server intergration error

- src/client/client.model.ts
Change the mongo model property - `teamid` to not be unique.
List general components of the application that this PR will affect:
* client.model
> fix: Fix mongo model teamid to not be unique.

- src/client/client.interface.ts
- src/client/client.model.ts
- src/client/client.validator.ts
- src/oauth2/oauth2.parser.ts
**READY**
Fixed client model parser, which is now suitable for web client.
> Client model

- src/client/client.model.ts
- src/oauth2/oauth2.parser.ts
**READY**
Added some values to the parse to clientInfo, and removed some unused mongo data.
> fix: Parse to ClientInformation add. Remove unused mongo data.

- src/client/client.controller.ts
**READY**
Fix a bug of the teamid param.
> fix: Fix teamId param that is used as req.teamId

- src/config.ts
**READY**
YES
Fixing the token config for requesting access token from authorization server
> fix: Fixing the token config for requesting access token Closes #78

- src/client/client.repository.ts
**READY**
Fix delete client functionality.
> fix: Fix Delete client not working issue.

- README.md
Rename `README.md` title from `ServerRegisterServer` to `SpikeServer`
> chore: Refactor README.md

- CONTRIBUTING.md
Rename `CONTRIBUTING.md` title from `serverregisterserver` to `SpikeServer`.
> chore: Refactor CONTRIBUTING.md

- package-lock.json
- package.json
- src/client/client.model.ts
- src/client/client.repository.spec.ts
- src/team/team.repository.spec.ts
**READY**
Add client repository unit tests.
> Client repo tests

- package-lock.json
- package.json
- src/app.ts
- src/client/client.repository.spec.ts
- src/config.ts
- src/oauth2/oauth2.controller.ts
- src/server.ts
- src/team/team.repository.spec.ts
> fix: Getting the project ready for deployment.

- package.json
- src/app.ts
- src/auth/auth.controller.ts
- src/config.ts
> fix: Fix errors of last commit. (DotEnv not loads)

- src/client/client.controller.ts
- src/oauth2/oauth2.controller.ts
- src/oauth2/oauth2.parser.ts
- tsconfig.json
**READY**
Refactor management API and decouple 3rd party requests from internal requests.
> Refactor and decouple management API

- src/app.ts
**READY**
Add /health route for IsAlive.
> Add /health route for IsAlive.

- src/config.ts
**READY**
Edit config structure.
> Edit config structure.

- src/client/client.repository.spec.ts
**READY**
Fix test not passed because of wrong checking method.
> Fix test not passed because of wrong checking method.

- src/oauth2/oauth2.parser.ts
**READY**
Fix environment issues.
> Fix environment issues.

- src/client/client.controller.ts
- src/client/client.interface.ts
- src/client/client.model.ts
- src/client/client.repository.spec.ts
- src/client/client.repository.ts
- src/client/client.validator.ts
- src/oauth2/oauth2.parser.ts
**READY**
YES
Bug fix for multiple hosts when updating with existing hosts (causing duplicates in array).
> Bug fix for multiple hosts duplicated in array

- src/client/client.controller.ts
- src/client/client.repository.ts
**READY**
Fix checking duplicate clients.
> Fix checking duplicate clients.

- package-lock.json
- package.json
- src/auth/auth.controller.ts
- src/client/client.controller.ts
- src/oauth2/oauth2.controller.ts
- src/server.ts
- src/team/team.controller.ts
- src/utils/logger.ts
> Logger feature has been added, and APM monitoring.

- src/client/client.controller.ts
- src/client/client.router.ts
- src/oauth2/oauth2.controller.ts
**READY**
Adding support for reset client credentials (id and secret)
> Adding support for reset client credentials (id and secret)
